name = "PerOrPol"
uuid = "80c1c646-5f8e-400d-957b-1aa7fb382189"
authors = ["czylabsonasa <czylabson.asa@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
